version: '2'

services:
  go:
    build: ./
    environment:
      - OXFORD_API_ID=${OXFORD_API_ID}
      - OXFORD_API_KEY=${OXFORD_API_KEY}
      - LINE_BOT_SECRET=${LINE_BOT_SECRET}
      - LINE_BOT_TOKEN=${LINE_BOT_TOKEN}
    ports:
      - '80:80'